# This is a basic workflow to help you get started with Actions

name: lambda-v2-deploy

on:
  workflow_run:
    workflows: ["lambda-v1-deploy"]   # Name of the workflow in bootstrap.yml
    branches:
      - main
    types:
      - completed           # Triggers after bootstrap completes

jobs:
  deploy:
    runs-on: ubuntu-latest
      - name: Checkout repository
        uses: actions/checkout@v4
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # integration with OIDC recommended
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # integration with OIDC recommended
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Update Lambda version1 function to version2
        run: |
          aws lambda update-function-code \
            --function-name python-lambda2 \
            --zip-file fileb://version2.zip

      - name: Check if Lambda version2 exists
        run: |
          set +e
          aws lambda get-function --function-name python-lambda2 --qualifier 2
          echo "existslambda=$?" >> $GITHUB_ENV

      - name: Create Lambda version v2
        if: env.existslambda == '254'  # Runs only if get-function failed (version1 does not exist)
        run: |
          aws lambda publish-version \
            --function-name python-lambda2 --description "v2"

      # - name: Zip Lambda - v1 code
      #   run: |
      #     aws lambda update-function-code \
      #       --function-name python-lambda \
      #       --zip-file fileb://version1.zip
